version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "47:6d:27:84:fe:b0:67:34:81:ce:2f:bf:90:ba:1a:0b"
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: download-libraries
          command: |
            go get -u
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: build docs
          command: |
            go run main.go
      - run:
          name: commit with skip
          command: |
            git commit -am "rebuilt docs [ci skip]" 